// Parsed club data → one idempotent SQL script.
//
// Emitting SQL rather than opening a connection is deliberate. `pg` is not a
// dependency of this project and adding one to import a spreadsheet twice would
// be a poor trade; piping into scripts/psql.sh instead reuses _env.sh, whose
// allowlist is the thing that stops a mistyped .env from writing club data into
// the president's live project. A generator also leaves the statements
// reviewable before they run.
//
// EVERY STATEMENT IS AN UPSERT. Running this twice must leave the same rows:
//
//   members     on conflict (lower(nickname))       — members_nickname_lower_uq
//   activities  on conflict (id)                    — ids are md5 of a stable key
//   attendance  on conflict (activity_id, member_id)
//   records     on conflict (member_id, stroke, subcategory, event_date,
//                            distance_m, result_centiseconds) — records_dedup_uq
//
// activities is the only table with no natural key, so its ids are derived from
// the thing they identify: md5('eysl-import:training:2026-01-04')::uuid. Same
// input, same uuid, so a second run updates rather than inserts.

import type { ClubData, ImportedRecord } from './parse.ts'

export type SqlOptions = {
  /** Named in the file header so a reader knows what produced these rows. */
  sourceLabel?: string
}

// --------------------------------------------------------------- SQL literals

/** A text literal. Empty string stays an empty string, not null. */
function lit(value: string): string {
  if (value.includes('\0')) throw new Error('NUL byte in a value bound for SQL')
  return `'${value.replace(/'/g, "''")}'`
}

/** A text literal, or SQL null when the value is empty. */
function litOrNull(value: string): string {
  return value === '' ? 'null' : lit(value)
}

function num(value: number | null): string {
  if (value === null) return 'null'
  if (!Number.isFinite(value)) throw new Error(`non-finite number bound for SQL: ${value}`)
  return String(value)
}

/** The deterministic id of an imported activity. */
function activityId(key: string): string {
  return `md5(${lit(`eysl-import:${key}`)})::uuid`
}

const trainingKey = (date: string) => `training:${date}`
const raceKey = (category: string, date: string, name: string) =>
  `race:${category}:${date}:${name}`

// ----------------------------------------------------------------- the script

export function toSql(data: ClubData, options: SqlOptions = {}): string {
  const out: string[] = []
  const source = options.sourceLabel ?? 'club master workbook'

  out.push(`-- Generated by scripts/import/run.ts from the ${source}.`)
  out.push('-- Idempotent: every statement is an upsert. Re-running changes nothing.')
  out.push('--')
  out.push('-- NOT FOR COMMIT. This script carries real member data; it is meant to be')
  out.push('-- piped straight into psql. See scripts/import-club-workbook.sh.')
  out.push('')
  out.push('\\set ON_ERROR_STOP on')
  out.push('begin;')
  out.push('')

  // -------------------------------------------------------------- marked_by
  //
  // attendance.marked_by is NOT NULL and references members(id) (0001:110).
  // It records who did the marking, and attendance_mark_v1 only lets staff mark
  // at all — so the honest filler is the administrator account running the
  // import, not a club member picked out of the roster. Attributing hundreds of
  // historical rows to a real member would assert something about them that the
  // workbook does not say.
  //
  // Resolved by role at load time rather than hardcoded, and it raises instead
  // of guessing when no administrator exists.
  //
  // NOT a pwtest account, and that exclusion is load-bearing rather than tidy.
  // e2e/cleanup.sql:34-36 deletes `attendance where marked_by in (pwtest
  // members)` before dropping those accounts, so naming pwtestadmin here would
  // hand every Playwright run a licence to delete the entire club register —
  // silently, since cleanup is meant to remove rows and would look like it
  // worked. The register has to be marked by somebody the test suite does not
  // own.
  out.push('-- Who is recorded as having marked the register. See the note in toSql.ts.')
  out.push('create temporary table _imp_ctx on commit drop as')
  out.push('select (select id from public.members')
  out.push("         where role = 'master_admin' and status = 'approved'")
  // e2e/cleanup.sql would take this import's attendance with it otherwise.
  out.push("           and nickname not like 'pwtest%'")
  out.push('         order by created_at, id limit 1) as admin_id;')
  out.push('')
  out.push('do $$')
  out.push('begin')
  out.push('  if (select admin_id from _imp_ctx) is null then')
  out.push(
    "    raise exception 'no approved master_admin member outside the pwtest prefix — " +
      "attendance.marked_by has nobody to name that e2e cleanup would not delete';",
  )
  out.push('  end if;')
  out.push('end $$;')
  out.push('')

  // ------------------------------------------------------------------ members
  if (data.members.length > 0) {
    out.push(`-- ${data.members.length} members from ☆명단(출석부).`)
    out.push('--')
    out.push('-- historical_attendance_count_legacy and historical_late_count_legacy stay 0')
    out.push('-- on purpose. The sheet has 상반기/지각/하반기/지각 counters, but 0016:155-157')
    out.push('-- ADDS those columns to a live count of attendance rows, and this import loads')
    out.push('-- the per-date grid those counters summarise — so carrying them over would')
    out.push('-- double every ranking. They are stale besides: one row reads 7 where the grid')
    out.push('-- holds 4.')
    out.push('insert into public.members (')
    out.push('  nickname, short_name, real_name, birth_year, birth_date_text, gender,')
    out.push('  join_date_text, join_reason, lesson_level, swim_experience, notes,')
    out.push('  status, role, historical_attendance_count_legacy, historical_late_count_legacy')
    out.push(') values')
    out.push(
      data.members
        .map(
          (m) =>
            `  (${lit(m.nickname)}, ${litOrNull(m.shortName)}, ${litOrNull(m.realName)}, ` +
            `${num(m.birthYear)}, ${litOrNull(m.birthDateText)}, ${litOrNull(m.gender)}, ` +
            `${litOrNull(m.joinDateText)}, ${litOrNull(m.joinReason)}, ${litOrNull(m.lessonLevel)}, ` +
            `${litOrNull(m.swimExperience)}, ${litOrNull(m.notes)}, 'approved', 'member', 0, 0)`,
        )
        .join(',\n'),
    )
    out.push('on conflict (lower(nickname)) do update set')
    out.push('  short_name      = excluded.short_name,')
    out.push('  real_name       = excluded.real_name,')
    out.push('  birth_year      = excluded.birth_year,')
    out.push('  birth_date_text = excluded.birth_date_text,')
    out.push('  gender          = excluded.gender,')
    out.push('  join_date_text  = excluded.join_date_text,')
    out.push('  join_reason     = excluded.join_reason,')
    out.push('  lesson_level    = excluded.lesson_level,')
    out.push('  swim_experience = excluded.swim_experience,')
    out.push('  notes           = excluded.notes,')
    // status and role are deliberately NOT overwritten: an admin who promoted
    // one of these members in the app would otherwise be demoted by the next
    // import, and a blocked member would be silently readmitted.
    out.push('  updated_at      = now();')
    out.push('')
  }

  // --------------------------------------------------------------- activities
  const activityRows: string[] = []
  for (const t of data.trainings) {
    const details = JSON.stringify({ source: 'club-workbook', half: t.half, label: t.label })
    activityRows.push(
      `  (${activityId(trainingKey(t.date))}, 'training', ${lit('정규 훈련')}, ` +
        `${lit(t.date)}, ${lit(details)})`,
    )
  }
  // The meets get activities too, so the 대회 screens have something in them.
  // records does not reference activities, so these are additive rather than
  // load-bearing — but a 대회 list that is empty while 기록 is full reads as a
  // broken screen.
  const seenRace = new Set<string>()
  for (const meet of data.meets) {
    const key = raceKey(meet.category, meet.date, meet.name)
    if (seenRace.has(key)) continue
    seenRace.add(key)
    const details = JSON.stringify({
      source: 'club-workbook',
      record_category: meet.category,
      date_source: meet.dateSource,
    })
    activityRows.push(
      `  (${activityId(key)}, 'race', ${lit(meet.name)}, ${lit(meet.date)}, ${lit(details)})`,
    )
  }

  if (activityRows.length > 0) {
    out.push(`-- ${data.trainings.length} trainings and ${seenRace.size} meets. Ids are md5 of a`)
    out.push('-- stable key, so a second run updates these rows instead of inserting new ones.')
    out.push('insert into public.activities (id, kind, title, activity_date, details, created_by)')
    out.push('select v.id, v.kind, v.title, v.activity_date::date, v.details::jsonb, c.admin_id')
    out.push('from (values')
    out.push(activityRows.join(',\n'))
    out.push(') as v(id, kind, title, activity_date, details)')
    out.push('cross join _imp_ctx c')
    out.push('on conflict (id) do update set')
    out.push('  kind          = excluded.kind,')
    out.push('  title         = excluded.title,')
    out.push('  activity_date = excluded.activity_date,')
    out.push('  details       = excluded.details,')
    out.push('  updated_at    = now();')
    out.push('')
  }

  // --------------------------------------------------------------- attendance
  //
  // A blank cell produces NO ROW, rather than an 'absent' one. Three reasons,
  // and the first is the one that decides it:
  //
  // 1. A blank is ambiguous. 17 of the 40 members joined during 2026, so their
  //    blanks in January mean 'not yet a member', not 'did not come'. The sheet
  //    also writes a literal '-' in a few early cells for exactly that case,
  //    which is the register admitting the distinction exists. An 'absent' row
  //    would assert a fact the source does not record.
  //
  // 2. 0030 widened attendance_for_activity_v1 to `applications ∪ marked`
  //    precisely because "the roster is what the pool deck actually looked like,
  //    and the application list is a prediction made beforehand". An absent row
  //    is not a pool-deck fact, it is the absence of one. Loading them would put
  //    every member on every historical roster and bury the rows that describe
  //    something that happened.
  //
  // 3. team_event_rankings_v1 counts `status in ('present','late')`, so absent
  //    rows change no ranking today — they would only add weight for any future
  //    query that forgets the filter.
  //
  // The cost is that a historical training's roster shows only the people who
  // came, since these activities have no activity_applications. That is the
  // correct reading of a paper register.
  if (data.attendance.length > 0) {
    const present = data.attendance.filter((a) => a.status === 'present').length
    out.push(
      `-- ${data.attendance.length} attendance rows (${present} present, ` +
        `${data.attendance.length - present} late). A blank imports as nothing at all —`,
    )
    out.push('-- see the long note in toSql.ts on why a blank is not an absence.')
    out.push('insert into public.attendance (activity_id, member_id, status, marked_by)')
    out.push('select v.activity_id, m.id, v.status, c.admin_id')
    out.push('from (values')
    out.push(
      data.attendance
        .map((a) => `  (${activityId(trainingKey(a.date))}, ${lit(a.nickname)}, ${lit(a.status)})`)
        .join(',\n'),
    )
    out.push(') as v(activity_id, nickname, status)')
    out.push('join public.members m on lower(m.nickname) = lower(v.nickname)')
    out.push('cross join _imp_ctx c')
    out.push('on conflict (activity_id, member_id) do update set')
    out.push('  status     = excluded.status,')
    out.push('  updated_at = now();')
    out.push('')
  }

  // ------------------------------------------------------------------ records
  const { rows: recordRows, dropped } = dedupeRecords(data.records)
  if (recordRows.length > 0) {
    out.push(`-- ${recordRows.length} personal results.`)
    if (dropped.length > 0) {
      out.push(`-- ${dropped.length} row(s) collapsed here rather than at the database: two`)
      out.push('-- results sharing records_dedup_uq inside one statement would raise')
      out.push('-- "ON CONFLICT DO UPDATE command cannot affect row a second time".')
    }
    out.push('--')
    out.push('-- 단체전 (relay) rows are NOT here. records.member_id is NOT NULL and the')
    out.push('-- 단체전 block names no swimmers, so there is nobody to attach them to.')
    out.push('insert into public.records (')
    out.push('  member_id, category, subcategory, stroke, distance_m, event_name,')
    out.push('  event_date, result_display, result_centiseconds, metadata, created_by')
    out.push(')')
    out.push('select m.id, v.category, v.subcategory, v.stroke, v.distance_m::int,')
    out.push('       v.event_name, v.event_date::date, v.result_display,')
    out.push('       v.result_centiseconds::int, v.metadata::jsonb, c.admin_id')
    out.push('from (values')
    out.push(
      recordRows
        .map((r) => {
          const metadata: Record<string, unknown> = { source: 'club-workbook' }
          if (r.memo) metadata.memo = r.memo
          if (r.dateSource !== 'label') metadata.date_source = r.dateSource
          if (r.distanceAssumed) metadata.distance_assumed = true
          return (
            `  (${lit(r.nickname)}, ${lit(r.category)}, ${lit(r.subcategory)}, ${lit(r.stroke)}, ` +
            `${num(r.distanceM)}, ${lit(r.eventName)}, ${lit(r.eventDate)}, ` +
            `${lit(r.resultDisplay)}, ${num(r.resultCentiseconds)}, ${lit(JSON.stringify(metadata))})`
          )
        })
        .join(',\n'),
    )
    out.push(') as v(nickname, category, subcategory, stroke, distance_m, event_name,')
    out.push('       event_date, result_display, result_centiseconds, metadata)')
    out.push('join public.members m on lower(m.nickname) = lower(v.nickname)')
    out.push('cross join _imp_ctx c')
    out.push(
      'on conflict (member_id, stroke, subcategory, event_date, distance_m, result_centiseconds)',
    )
    out.push('do update set')
    out.push('  category   = excluded.category,')
    out.push('  event_name = excluded.event_name,')
    out.push('  metadata   = excluded.metadata,')
    out.push('  updated_at = now();')
    out.push('')
  }

  out.push('commit;')
  out.push('')

  // ------------------------------------------------------------- verification
  //
  // Read back rather than trusting the insert. An INSERT that reports success
  // and a SELECT that returns the rows are different claims.
  out.push('-- Read back what actually landed.')
  out.push("\\echo ''")
  out.push("\\echo '== imported row counts =='")
  // 'non-pwtest' rather than 'imported': members has no column marking where a
  // row came from, so this count also includes any admin account that was
  // already there. Saying what is actually counted beats a tidier label that
  // would overstate by two and invite somebody to chase the difference.
  out.push("select 'members (non-pwtest)' as what, count(*) as n from public.members")
  out.push("  where nickname not like 'pwtest%'")
  out.push('union all')
  out.push("select 'activities: ' || kind, count(*) from public.activities")
  out.push("  where details->>'source' = 'club-workbook' group by kind")
  out.push('union all')
  out.push("select 'attendance: ' || a.status, count(*) from public.attendance a")
  out.push('  join public.activities act on act.id = a.activity_id')
  out.push("  where act.details->>'source' = 'club-workbook' group by a.status")
  out.push('union all')
  out.push("select 'records: ' || category || '/' || subcategory, count(*) from public.records")
  out.push("  where metadata->>'source' = 'club-workbook' group by category, subcategory")
  out.push('order by 1;')

  return out.join('\n') + '\n'
}

/**
 * Collapses results that would collide on records_dedup_uq.
 *
 * Postgres refuses an INSERT whose own VALUES list hits the same conflict key
 * twice — "ON CONFLICT DO UPDATE command cannot affect row a second time" — so
 * the collapse has to happen here, before the statement is built. It is not
 * hypothetical: the 핀 section repeats 2026 수원 연맹회장배 on the same date as
 * the 일반 section, and records_dedup_uq does not include category.
 */
export function dedupeRecords(records: ImportedRecord[]): {
  rows: ImportedRecord[]
  dropped: ImportedRecord[]
} {
  const rows: ImportedRecord[] = []
  const dropped: ImportedRecord[] = []
  const seen = new Set<string>()

  for (const r of records) {
    // JSON rather than a joined string: a stroke containing the separator would
    // otherwise let two different keys collide.
    const key = JSON.stringify([
      r.nickname.toLowerCase(),
      r.stroke,
      r.subcategory,
      r.eventDate,
      r.distanceM,
      r.resultCentiseconds,
    ])
    if (seen.has(key)) dropped.push(r)
    else {
      seen.add(key)
      rows.push(r)
    }
  }

  return { rows, dropped }
}
