-- ============================================================================
-- A chat attachment keeps the name the sender chose.
--
-- 0042 made object keys ASCII, because Supabase Storage answers 400 InvalidKey
-- for a key containing Hangul and every upload in the app was failing for the
-- ordinary Korean filename. That fix was right and it took something with it:
-- the key WAS the display name. Every other claim table already kept the
-- readable name in a column of its own --
--
--     notice_attachments.file_name
--     media_files.file_name
--     record_uploads.file_name
--     messages                       <- nothing
--
-- -- so `messages` is the one place where the slug is all that is left. A member
-- who sends 훈련일지.txt with no caption now sees `file.txt`, because
-- MessageThread falls back to the last segment of the storage path.
--
-- NOT A DEFECT 0042 INTRODUCED. It is a place 0042 exposed: the name and the key
-- were the same string, so nothing had to decide where the name lived until the
-- key stopped being able to hold it. This migration decides.
-- ============================================================================

-- Nullable with no default and no backfill, deliberately. Every existing row
-- predates the column and there is nothing truthful to put in it -- inventing a
-- name from the storage path would write the slug into the very column meant to
-- hold what the slug lost. A null here reads as "not recorded", and the render
-- falls back exactly as it does today.
alter table public.messages
  add column if not exists attachment_name text;

comment on column public.messages.attachment_name is
  '보낸 사람이 고른 원래 파일명. 저장소 키는 ASCII로 슬러그되므로(0042) 표시용 이름은 여기에만 남는다. 예전 행은 null이고, 그때는 화면이 경로 마지막 조각으로 대체한다.';

-- ---------------------------------------------------------------- the writer
-- Taken VERBATIM from 0029 and changed in exactly three places: the new
-- parameter, its variable, and the insert. The body is not retyped -- 0024 lost
-- p_user_agent that way, and the guard against repeating it is mechanical rather
-- than careful: this file was generated by extracting 0029's block and asserting
-- each substitution matched exactly once.
create or replace function public.send_message_v1(
  p_room_type       text,
  p_body            text default null,
  p_recipient_id    uuid default null,
  p_attachment_path text default null,
  p_attachment_type text default null,
  -- NEW in 0049. Defaulted, so every existing call still resolves.
  p_attachment_name text default null
)
returns public.messages
language plpgsql security definer set search_path = public
as $$
declare
  v_sender     uuid;
  v_body       text;
  v_attachment text;
  v_name       text;
  v_row        public.messages;
begin
  v_sender := public.current_member_id();
  if v_sender is null then
    raise exception 'not an approved member' using errcode = '42501';
  end if;

  if p_room_type is null or p_room_type not in ('group', 'dm') then
    raise exception 'invalid room_type: %', coalesce(p_room_type, '(null)') using errcode = '22023';
  end if;

  -- recipient_matches_room_type (0004:146-147) already says this, but a CHECK
  -- violation surfaces as 23514 naming a constraint. Raising first turns the
  -- same rule into a sentence a screen can show without translating pgcodes.
  if p_room_type = 'dm' and p_recipient_id is null then
    raise exception 'a direct message needs a recipient' using errcode = '22023';
  end if;
  if p_room_type = 'group' and p_recipient_id is not null then
    raise exception 'a group message cannot have a recipient' using errcode = '22023';
  end if;

  if p_room_type = 'dm' then
    if p_recipient_id = v_sender then
      raise exception 'cannot send a direct message to yourself' using errcode = '22023';
    end if;
    -- Approved, not merely present. current_member_id() stops answering for a
    -- blocked member (0001:123-129), so a DM addressed to one would be a row
    -- only the sender could ever read.
    if not exists (
      select 1 from public.members
       where id = p_recipient_id and status = 'approved'
    ) then
      raise exception 'no such approved member' using errcode = '23503';
    end if;
  end if;

  -- Trim before the emptiness test, not after. body_or_attachment (0004:148-149)
  -- compares against '' and a body of three spaces satisfies it — a message that
  -- passes the constraint and renders as an empty bubble.
  v_body       := nullif(btrim(coalesce(p_body, '')), '');
  v_attachment := nullif(btrim(coalesce(p_attachment_path, '')), '');

  if v_body is null and v_attachment is null then
    raise exception 'a message needs text or an attachment' using errcode = '22023';
  end if;

  -- THE NEW GUARD. An attachment must be a file this sender could have uploaded.
  -- Without it, naming a path is enough to gain read access to it — see the
  -- measurement above is_my_team_file_path.
  --
  -- 42501 rather than 22023: this is not a malformed argument, it is a refusal of
  -- authority, and it should read like one in a log.
  if v_attachment is not null and not public.is_my_team_file_path(v_attachment) then
    raise exception 'an attachment must be a file you uploaded' using errcode = '42501';
  end if;

  -- The column is unbounded text. Nothing in the app can send more than a
  -- composer holds, but nothing in the app is what a hostile client uses.
  if length(v_body) > 4000 then
    raise exception 'message is too long (max 4000 characters)' using errcode = '22001';
  end if;

  -- Trimmed and capped like the body. A name is display text, so the ceiling is
  -- about what a bubble can show rather than what storage can hold; 200 is far
  -- past any real file name and far short of anything that could crowd a screen.
  v_name := left(nullif(btrim(coalesce(p_attachment_name, '')), ''), 200);

  insert into public.messages (
    room_type, sender_id, recipient_id, body,
    attachment_path, attachment_type, attachment_name
  ) values (
    p_room_type,
    v_sender,
    case when p_room_type = 'dm' then p_recipient_id end,
    v_body,
    v_attachment,
    -- A type without a path describes nothing, so it is dropped rather than
    -- stored beside a null attachment.
    case when v_attachment is null then null
         else nullif(btrim(coalesce(p_attachment_type, '')), '') end,
    -- And a name without a path describes nothing either, for the same reason.
    case when v_attachment is null then null else v_name end
  )
  returning * into v_row;

  return v_row;
end $$;

comment on function public.send_message_v1(text, text, uuid, text, text, text) is
  '메시지 보내기. 보낸 사람은 세션에서 읽고, 첨부 경로는 본인이 올린 파일만 허용하며, 원래 파일명은 표시용으로 함께 저장한다.';

-- THE FIVE-ARGUMENT FORM IS DROPPED, and this is the half that is easy to skip.
-- `create or replace` cannot change a signature, so without this the old
-- function would still exist and still be callable -- a second, silently
-- name-less writer sitting beside the new one. 0040 hit exactly this with
-- save_notice_v1's four-argument form, where what survived was the version with
-- no conflict check; here what would survive is merely worse rather than
-- dangerous, but an overload nobody meant to keep is how the dangerous case
-- arrives next time.
--
-- Safe to drop: the parameter is defaulted, so every existing five-argument call
-- resolves against the new six-argument function.
drop function if exists public.send_message_v1(text, text, uuid, text, text);

-- Restated so a replace cannot quietly widen it -- 0029's reasoning, applied to
-- the new signature rather than the old one.
revoke all on function public.send_message_v1(text, text, uuid, text, text, text)
  from public, anon, authenticated;
grant execute on function public.send_message_v1(text, text, uuid, text, text, text)
  to authenticated;
